import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  autowhitelist: [
    {
      type: 'autogenerated',
      dirName: 'minecraft/autowhitelist',
    },
  ],
};

export default sidebars;
